# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files


  # flake8 formatter
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: [--max-line-length=120]

  # black formatter
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args: [--line-length=120]



  # prettier formatter
  #- repo: https://github.com/pre-commit/mirrors-prettier
  #  rev: v2.5.1
  #  hooks:
  #    - id: prettier
  #      files: \.(json|markdown|md|yaml|yml)$
